name: ey_challenge
channels:
  - defaults
  - pytorch
dependencies:
  # - torch==1.3.0.post2
  - python=3.8
  - tqdm
  - jupyter
  - python-graphviz
  - matplotlib 
  - pandas
  - scikit-learn
  - seaborn
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - scikit-image
    - pystac
    - rich
    - ipyleaflet
    - torchmetrics
    - torch==1.12.1+cu113 
    - torchvision==0.13.1+cu113 
    - pytorch-ssim==0.1
    - opencv-python==4.5.1.48
    - pystac_client
    - planetary-computer
    - odc-stac
    - charset-normalizer==2.1.0
    - rioxarray==0.13.3
    - stackstac-0.4.3
    - xarray-spatial
    - odc-algo
    # - torch==1.4.0
    # - torchvision==0.5.0